### ISSUE TITLE
Move Cursor Code Causes Issues

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#105]
**Expected behavior**
When the cursor is moved another ANSI code should be accepted.

**Actual behavior**
Graphical garbage is printed and the next character (if an integer) is ignored.

**Screenshot**

![](https://github.com/Kfeavel/BugReport/blob/master/Expected.png?raw=true)

![](https://github.com/Kfeavel/BugReport/blob/master/Unexpected.png?raw=true)

**Bad Code (Should Work):**
`px_kprintf("\033[0;%iH\033[31mStack trace:\033[0m\n", (X86_TTY_WIDTH - 16));`

**Good Code (Work Around):**
`px_kprintf("\033[0;%iH \033[31mStack trace:\033[0m\n", (X86_TTY_WIDTH - 16));`

**Comment by micahswitzer** [comment]
Would it be possible for you to provide a screenshot of the issue? Maybe that is something we should add to our issue template.

**Comment by Kfeavel** [comment]
The default template does include a section for screenshots. I just didn't include one because I was wrapping up for the night. I'll include it later with code examples.

**Comment by Kfeavel** [comment]
Updated with images.

**Comment by micahswitzer** [comment]
The issue is that the state is not reset to `Normal` after the escape code has been processed. [See this `if` block](https://github.com/panix-os-dev-team/Panix/blob/fdb51bd7701b982aea402ee49f84c7a827c1ecd1/kernel/lib/putchar.cpp#L102) and note that it does not reset the state like the block above it.
