### ISSUE TITLE
Critical Region Mutexing

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#160]
Add mutexes / semaphores to critical areas of kernel

- [x] TTY / VGA Printing
- [x] Memory allocation / freeing
- [x] Serial IO

**Comment by Kfeavel** [comment]
Wait, doesn't our heap already have mutual exclusion support due to liballoc? `liballoc_lock()` and `liballoc_unlock()` are already implemented. Do we want to add additional mutex to the paging code too? (cc @micahswitzer)

**Comment by micahswitzer** [comment]
Yeah I did add a mutex to the liballoc code. We probably should add locking to the paging code, but maybe only the code that actually looks up which pages are free since nothing else (even the free) technically requires a lock. Basically just think about what would happen if the code was preempted at any point in time and whether or not that would have any bad effects.

**Comment by Kfeavel** [comment]
Updated in fa3c80f
